export const flashcards = [
    { word: "der / die / das", meaning: "the; that, those; who, that" },
    { word: "und", meaning: "and" },
    { word: "sein", meaning: "to be" },
    { word: "in", meaning: "in" },
    { word: "ein", meaning: "a, an; one" },
    { word: "zu", meaning: "to, at; too" },
    { word: "haben", meaning: "to have" },
    { word: "ich", meaning: "I" },
    { word: "werden", meaning: "to become" },
    { word: "sie", meaning: "she, her; they, them; you" },
    { word: "von", meaning: "from, of" },
    { word: "nicht", meaning: "not" },
    { word: "mit", meaning: "with" },
    { word: "es", meaning: "it" },
    { word: "sich", meaning: "self" },
    { word: "auch", meaning: "also, too" },
    { word: "auf", meaning: "on, at, in" },
    { word: "für", meaning: "for" },
    { word: "an", meaning: "at, on" },
    { word: "er", meaning: "he" },
    { word: "so", meaning: "so; thus, this way, such" },
    { word: "dass", meaning: "that" },
    { word: "können", meaning: "can, to be able" },
    { word: "dies-", meaning: "this, that" },
    { word: "als", meaning: "as, when; than" },
    { word: "ihr", meaning: "you, her; her, their, hers, theirs; your" },
    { word: "ja", meaning: "yes; certainly, really" },
    { word: "wie", meaning: "how; as" },
    { word: "bei", meaning: "by, with, at" },
    { word: "oder", meaning: "or" },
    { word: "wir", meaning: "we" },
    { word: "aber", meaning: "but" },
    { word: "dann", meaning: "then" },
    { word: "man", meaning: "one, you" },
    { word: "da", meaning: "there; because" },
    { word: "sein", meaning: "his, its" },
    { word: "noch", meaning: "still, yet" },
    { word: "nach", meaning: "after, toward" },
    { word: "was", meaning: "what" },
    { word: "also", meaning: "so, therefore" },
    { word: "aus", meaning: "out, out of, from" },
    { word: "all", meaning: "all" },
    { word: "wenn", meaning: "if, when" },
    { word: "nur", meaning: "only" },
    { word: "müssen", meaning: "to have to, must" },
    { word: "sagen", meaning: "to say" },
    { word: "um", meaning: "around, at" },
    { word: "über", meaning: "above, over, about" },
    { word: "machen", meaning: "to do, make" },
    { word: "kein", meaning: "no, not a/an" },
    { word: "Jahr das, -e", meaning: "year" },
    { word: "du", meaning: "you" },
    { word: "mein", meaning: "my" },
    { word: "schon", meaning: "already" },
    { word: "vor", meaning: "in front of, before, ago" },
    { word: "durch", meaning: "through" },
    { word: "geben", meaning: "to give" },
    { word: "mehr", meaning: "more" },
    { word: "andere, anderer, anderes", meaning: "other" },
    { word: "viel", meaning: "much, a lot, many" },
    { word: "kommen", meaning: "to come" },
    { word: "jetzt", meaning: "now" },
    { word: "sollen", meaning: "should, ought to" },
    { word: "mir", meaning: "me" },
    { word: "wollen", meaning: "to want" },
    { word: "ganz", meaning: "whole, all the; quite" },
    { word: "mich", meaning: "me" },
    { word: "immer", meaning: "always" },
    { word: "gehen", meaning: "to go" },
    { word: "sehr", meaning: "very" },
    { word: "hier", meaning: "here" },
    { word: "doch", meaning: "however, still" },
    { word: "bis", meaning: "until" },
    { word: "groß", meaning: "big, large, great" },
    { word: "wieder", meaning: "again" },
    { word: "Mal das, -e", meaning: "time" },
    { word: "zwei", meaning: "two" },
    { word: "gut", meaning: "good" },
    { word: "wissen", meaning: "to know" },
    { word: "neu", meaning: "new" },
    { word: "sehen", meaning: "to see" },
    { word: "lassen", meaning: "to let, allow, have something done" },
    { word: "uns", meaning: "us" },
    { word: "weil", meaning: "because" },
    { word: "unter", meaning: "under" },
    { word: "denn", meaning: "because" },
    { word: "stehen", meaning: "to stand" },
    { word: "jed-", meaning: "every, each" },
    { word: "Beispiel, das, -e", meaning: "example" },
    { word: "Zeit, die", meaning: "time" },
    { word: "erste, erster, erstes", meaning: "first" },
    { word: "ihm", meaning: "him, it" },
    { word: "ihn", meaning: "him" },
    { word: "wo", meaning: "where" },
    { word: "lang", meaning: "long; for a long time" },
    { word: "eigentlich", meaning: "actually; actual, real" },
    { word: "damit", meaning: "with it; so that" },
    { word: "selbst, selber", meaning: "self; even" },
    { word: "unser", meaning: "our" },
    { word: "oben", meaning: "above, up there" },
    { word: "drei", meaning: "three" },
    { word: "wenig", meaning: "few, little" },
    { word: "Frau", meaning: "woman, wife, Mrs." },
    { word: "Mensch", meaning: "human being, person" },
    { word: "deutsch", meaning: "German; German (language)" },
    { word: "Kind", meaning: "child" },
    { word: "etwas", meaning: "something, some, a little" },
    { word: "Tag", meaning: "day" },
    { word: "nun", meaning: "now" },
    { word: "finden", meaning: "to find" },
    { word: "nichts", meaning: "nothing" },
    { word: "bleiben", meaning: "to stay" },
    { word: "sondern", meaning: "but (on the contrary)" },
    { word: "klein", meaning: "small, little" },
    { word: "zwischen", meaning: "between" },
    { word: "alt", meaning: "old" },
    { word: "gegen", meaning: "against" },
    { word: "liegen", meaning: "to lie" },
    { word: "ohne", meaning: "without" },
    { word: "nein", meaning: "no" },
    { word: "heute", meaning: "today" },
    { word: "weit", meaning: "wide, far" },
    { word: "heißen", meaning: "to be called" },
    { word: "denken", meaning: "to think" },
    { word: "eben", meaning: "just now, simply, exactly" },
    { word: "erst", meaning: "first, only, not until; only now, already, more so" },
    { word: "natürlich", meaning: "naturally, of course" },
    { word: "ob", meaning: "whether" },
    { word: "hoch", meaning: "high" },
    { word: "beide", meaning: "both" },
    { word: "Mann", meaning: "man" },
    { word: "einfach", meaning: "simple, easy; simply" },
    { word: "vielleicht", meaning: "maybe, perhaps; really" },
    { word: "dort", meaning: "there" },
    { word: "dabei", meaning: "with it; there, in the process" },
    { word: "einmal", meaning: "once" },
    { word: "ihnen", meaning: "to/for them; to/for you (formal)" },
    { word: "welch-", meaning: "which" },
    { word: "nehmen", meaning: "to take" },
    { word: "tun", meaning: "to do" },
    { word: "seit", meaning: "since, for" },
    { word: "dürfen", meaning: "to be allowed, may" },
    { word: "glauben", meaning: "to believe" },
    { word: "halten", meaning: "to stop, hold" },
    { word: "nennen", meaning: "to name, call" },
    { word: "Land", meaning: "land, country, state" },
    { word: "letzt-", meaning: "last" },
    { word: "gleich", meaning: "same; right away, just" },
    { word: "solch-", meaning: "such" },
    { word: "dazu", meaning: "in addition, furthermore, to that" },
    { word: "mögen", meaning: "to like" },
    { word: "Frage", meaning: "question" },
    { word: "gar", meaning: "at all" },
    { word: "zeigen", meaning: "to show" },
    { word: "führen", meaning: "to lead" },
    { word: "möglich", meaning: "possible" },
    { word: "sprechen", meaning: "to speak" },
    { word: "während", meaning: "during; while, whereas" },
    { word: "Haus", meaning: "house" },
    { word: "Fall", meaning: "case; fall" },
    { word: "eigen", meaning: "one's own" },
    { word: "bringen", meaning: "to bring, take" },
    { word: "Leute", meaning: "people" },
    { word: "schön", meaning: "beautiful, pleasant, good" },
    { word: "einige", meaning: "a few, some" },
    { word: "bereits", meaning: "already" },
    { word: "Arbeit", meaning: "work" },
    { word: "leben", meaning: "to live" },
    { word: "fahren", meaning: "to drive, ride, go" },
    { word: "meinen", meaning: "to think, have an opinion" },
    { word: "spät", meaning: "late" },
    { word: "etwa", meaning: "about, approximately; perhaps" },
    { word: "wer", meaning: "who, whoever" },
    { word: "Prozent", meaning: "percent" },
    { word: "fragen", meaning: "to ask" },
    { word: "gerade", meaning: "just, just now; straight" },
    { word: "wichtig", meaning: "important" },
    { word: "zwar", meaning: "admittedly, to be precise" },
    { word: "Hand", meaning: "hand" },
    { word: "wirklich", meaning: "real, actual" },
    { word: "kennen", meaning: "to know" },
    { word: "weitere", meaning: "additional" },
    { word: "genau", meaning: "exact" },
    { word: "jung", meaning: "young" },
    { word: "gelten", meaning: "to be valid" },
    { word: "Stadt", meaning: "city" },
    { word: "Herr", meaning: "gentleman, Mr." },
    { word: "Teil", meaning: "part" },
    { word: "Problem", meaning: "problem" },
    { word: "Welt", meaning: "world" },
    { word: "jedoch", meaning: "however" },
    { word: "stellen", meaning: "to place, set" },
    { word: "darauf", meaning: "on it, to it" },
    { word: "bisschen", meaning: "little bit" },
    { word: "vier", meaning: "four" },
    { word: "nie", meaning: "never" },
    { word: "spielen", meaning: "to play" },
    { word: "denen", meaning: "to/for whom/that" },
    { word: "Recht", meaning: "right, law; all right; rather" },
    { word: "arbeiten", meaning: "to work" }
  ];