const flashcards = [
    { word: "der / die / das", meaning: "the; that, those; who, that" },
    { word: "und", meaning: "and" },
    { word: "sein", meaning: "to be" },
    { word: "in", meaning: "in" },
    { word: "ein", meaning: "a, an; one" },
    { word: "zu", meaning: "to, at; too" },
    { word: "haben", meaning: "to have" },
    { word: "ich", meaning: "I" },
    { word: "werden", meaning: "to become" },
    { word: "sie", meaning: "she, her; they, them; you" },
    { word: "von", meaning: "from, of" },
    { word: "nicht", meaning: "not" },
    { word: "mit", meaning: "with" },
    { word: "es", meaning: "it" },
    { word: "sich", meaning: "self" },
    { word: "auch", meaning: "also, too" },
    { word: "auf", meaning: "on, at, in" },
    { word: "für", meaning: "for" },
    { word: "an", meaning: "at, on" },
    { word: "er", meaning: "he" },
    { word: "so", meaning: "so; thus, this way, such" },
    { word: "dass", meaning: "that" },
    { word: "können", meaning: "can, to be able" },
    { word: "dies-", meaning: "this, that" },
    { word: "als", meaning: "as, when; than" },
    { word: "ihr", meaning: "you, her; her, their, hers, theirs; your" },
    { word: "ja", meaning: "yes; certainly, really" },
    { word: "wie", meaning: "how; as" },
    { word: "bei", meaning: "by, with, at" },
    { word: "oder", meaning: "or" },
    { word: "wir", meaning: "we" },
    { word: "aber", meaning: "but" },
    { word: "dann", meaning: "then" },
    { word: "man", meaning: "one, you" },
    { word: "da", meaning: "there; because" },
    { word: "sein", meaning: "his, its" },
    { word: "noch", meaning: "still, yet" },
    { word: "nach", meaning: "after, toward" },
    { word: "was", meaning: "what" },
    { word: "also", meaning: "so, therefore" },
    { word: "aus", meaning: "out, out of, from" },
    { word: "all", meaning: "all" },
    { word: "wenn", meaning: "if, when" },
    { word: "nur", meaning: "only" },
    { word: "müssen", meaning: "to have to, must" },
    { word: "sagen", meaning: "to say" },
    { word: "um", meaning: "around, at" },
    { word: "über", meaning: "above, over, about" },
    { word: "machen", meaning: "to do, make" },
    { word: "kein", meaning: "no, not a/an" },
    { word: "Jahr das, -e", meaning: "year" },
    { word: "du", meaning: "you" },
    { word: "mein", meaning: "my" },
    { word: "schon", meaning: "already" },
    { word: "vor", meaning: "in front of, before, ago" },
    { word: "durch", meaning: "through" },
    { word: "geben", meaning: "to give" },
    { word: "mehr", meaning: "more" },
    { word: "andere, anderer, anderes", meaning: "other" },
    { word: "viel", meaning: "much, a lot, many" },
    { word: "kommen", meaning: "to come" },
    { word: "jetzt", meaning: "now" },
    { word: "sollen", meaning: "should, ought to" },
    { word: "mir", meaning: "me" },
    { word: "wollen", meaning: "to want" },
    { word: "ganz", meaning: "whole, all the; quite" },
    { word: "mich", meaning: "me" },
    { word: "immer", meaning: "always" },
    { word: "gehen", meaning: "to go" },
    { word: "sehr", meaning: "very" },
    { word: "hier", meaning: "here" },
    { word: "doch", meaning: "however, still" },
    { word: "bis", meaning: "until" },
    { word: "groß", meaning: "big, large, great" },
    { word: "wieder", meaning: "again" },
    { word: "Mal das, -e", meaning: "time" },
    { word: "zwei", meaning: "two" },
    { word: "gut", meaning: "good" },
    { word: "wissen", meaning: "to know" },
    { word: "neu", meaning: "new" },
    { word: "sehen", meaning: "to see" },
    { word: "lassen", meaning: "to let, allow, have something done" },
    { word: "uns", meaning: "us" },
    { word: "weil", meaning: "because" },
    { word: "unter", meaning: "under" },
    { word: "denn", meaning: "because" },
    { word: "stehen", meaning: "to stand" },
    { word: "jed-", meaning: "every, each" },
    { word: "Beispiel, das, -e", meaning: "example" },
    { word: "Zeit, die", meaning: "time" },
    { word: "erste, erster, erstes", meaning: "first" },
    { word: "ihm", meaning: "him, it" },
    { word: "ihn", meaning: "him" },
    { word: "wo", meaning: "where" },
    { word: "lang", meaning: "long; for a long time" },
    { word: "eigentlich", meaning: "actually; actual, real" },
    { word: "damit", meaning: "with it; so that" },
    { word: "selbst, selber", meaning: "self; even" },
    { word: "unser", meaning: "our" },
    { word: "oben", meaning: "above, up there" }
  ];
  