export const flashcards = [
    { word: "der / die / das", meaning: "the; that, those; who, that" },
    { word: "und", meaning: "and" },
    { word: "zu sein", meaning: "to be" },
    { word: "in", meaning: "in" },
    { word: "ein", meaning: "a, an; one" },
    { word: "zu", meaning: "to, at; too" },
    { word: "haben", meaning: "to have" },
    { word: "ich", meaning: "I" },
    { word: "werden", meaning: "to become" },
    { word: "sie", meaning: "she, her; they, them; you" },
    { word: "von", meaning: "from, of" },
    { word: "nicht", meaning: "not" },
    { word: "mit", meaning: "with" },
    { word: "es", meaning: "it" },
    { word: "sich", meaning: "self" },
    { word: "auch", meaning: "also, too" },
    { word: "auf", meaning: "on, at, in" },
    { word: "für", meaning: "for" },
    { word: "an", meaning: "at, on" },
    { word: "er", meaning: "he" },
    { word: "so", meaning: "so; thus, this way, such" },
    { word: "dass", meaning: "that" },
    { word: "können", meaning: "can, to be able" },
    { word: "dies-", meaning: "this, that" },
    { word: "als", meaning: "as, when; than" },
    { word: "ihr", meaning: "you, her; her, their, hers, theirs; your" },
    { word: "ja", meaning: "yes; certainly, really" },
    { word: "wie", meaning: "how; as" },
    { word: "bei", meaning: "by, with, at" },
    { word: "oder", meaning: "or" },
    { word: "wir", meaning: "we" },
    { word: "aber", meaning: "but" },
    { word: "dann", meaning: "then" },
    { word: "man", meaning: "one, you" },
    { word: "da", meaning: "there; because" },
    { word: "sein", meaning: "his, its" },
    { word: "noch", meaning: "still, yet" },
    { word: "nach", meaning: "after, toward" },
    { word: "was", meaning: "what" },
    { word: "also", meaning: "so, therefore" },
    { word: "aus", meaning: "out, out of, from" },
    { word: "all", meaning: "all" },
    { word: "wenn", meaning: "if, when" },
    { word: "nur", meaning: "only" },
    { word: "müssen", meaning: "to have to, must" },
    { word: "sagen", meaning: "to say" },
    { word: "um", meaning: "around, at" },
    { word: "über", meaning: "above, over, about" },
    { word: "machen", meaning: "to do, make" },
    { word: "kein", meaning: "no, not a/an" },
    { word: "Jahr das, -e", meaning: "year" },
    { word: "du", meaning: "you" },
    { word: "mein", meaning: "my" },
    { word: "schon", meaning: "already" },
    { word: "vor", meaning: "in front of, before, ago" },
    { word: "durch", meaning: "through" },
    { word: "geben", meaning: "to give" },
    { word: "mehr", meaning: "more" },
    { word: "andere, anderer, anderes", meaning: "other" },
    { word: "viel", meaning: "much, a lot, many" },
    { word: "kommen", meaning: "to come" },
    { word: "jetzt", meaning: "now" },
    { word: "sollen", meaning: "should, ought to" },
    { word: "mir", meaning: "me" },
    { word: "wollen", meaning: "to want" },
    { word: "ganz", meaning: "whole, all the; quite" },
    { word: "mich", meaning: "me" },
    { word: "immer", meaning: "always" },
    { word: "gehen", meaning: "to go" },
    { word: "sehr", meaning: "very" },
    { word: "hier", meaning: "here" },
    { word: "doch", meaning: "however, still" },
    { word: "bis", meaning: "until" },
    { word: "groß", meaning: "big, large, great" },
    { word: "wieder", meaning: "again" },
    { word: "Mal das, -e", meaning: "time" },
    { word: "zwei", meaning: "two" },
    { word: "gut", meaning: "good" },
    { word: "wissen", meaning: "to know" },
    { word: "neu", meaning: "new" },
    { word: "sehen", meaning: "to see" },
    { word: "lassen", meaning: "to let, allow, have something done" },
    { word: "uns", meaning: "us" },
    { word: "weil", meaning: "because" },
    { word: "unter", meaning: "under" },
    { word: "denn", meaning: "because" },
    { word: "stehen", meaning: "to stand" },
    { word: "jed-", meaning: "every, each" },
    { word: "Beispiel", meaning: "example" },
    { word: "Zeit, die", meaning: "time" },
    { word: "erste, erster, erstes", meaning: "first" },
    { word: "ihm", meaning: "him, it" },
    { word: "ihn", meaning: "him" },
    { word: "wo", meaning: "where" },
    { word: "lang", meaning: "long; for a long time" },
    { word: "eigentlich", meaning: "actually; actual, real" },
    { word: "damit", meaning: "with it; so that" },
    { word: "selbst, selber", meaning: "self; even" },
    { word: "unser", meaning: "our" },
    { word: "oben", meaning: "above, up there" },
    { word: "drei", meaning: "three" },
    { word: "wenig", meaning: "few, little" },
    { word: "Frau", meaning: "woman, wife, Mrs." },
    { word: "Mensch", meaning: "human being, person" },
    { word: "deutsch", meaning: "German; German (language)" },
    { word: "Kind", meaning: "child" },
    { word: "etwas", meaning: "something, some, a little" },
    { word: "Tag", meaning: "day" },
    { word: "nun", meaning: "now" },
    { word: "finden", meaning: "to find" },
    { word: "nichts", meaning: "nothing" },
    { word: "bleiben", meaning: "to stay" },
    { word: "sondern", meaning: "but (on the contrary)" },
    { word: "klein", meaning: "small, little" },
    { word: "zwischen", meaning: "between" },
    { word: "alt", meaning: "old" },
    { word: "gegen", meaning: "against" },
    { word: "liegen", meaning: "to lie" },
    { word: "ohne", meaning: "without" },
    { word: "nein", meaning: "no" },
    { word: "heute", meaning: "today" },
    { word: "weit", meaning: "wide, far" },
    { word: "heißen", meaning: "to be called" },
    { word: "denken", meaning: "to think" },
    { word: "eben", meaning: "just now, simply, exactly" },
    { word: "erst", meaning: "first, only, not until; only now, already, more so" },
    { word: "natürlich", meaning: "naturally, of course" },
    { word: "ob", meaning: "whether" },
    { word: "hoch", meaning: "high" },
    { word: "beide", meaning: "both" },
    { word: "Mann", meaning: "man" },
    { word: "einfach", meaning: "simple, easy; simply" },
    { word: "vielleicht", meaning: "maybe, perhaps; really" },
    { word: "dort", meaning: "there" },
    { word: "dabei", meaning: "with it; there, in the process" },
    { word: "einmal", meaning: "once" },
    { word: "ihnen", meaning: "to/for them; to/for you (formal)" },
    { word: "welch-", meaning: "which" },
    { word: "nehmen", meaning: "to take" },
    { word: "tun", meaning: "to do" },
    { word: "seit", meaning: "since, for" },
    { word: "dürfen", meaning: "to be allowed, may" },
    { word: "glauben", meaning: "to believe" },
    { word: "halten", meaning: "to stop, hold" },
    { word: "nennen", meaning: "to name, call" },
    { word: "Land", meaning: "land, country, state" },
    { word: "letzt-", meaning: "last" },
    { word: "gleich", meaning: "same; right away, just" },
    { word: "solch-", meaning: "such" },
    { word: "dazu", meaning: "in addition, furthermore, to that" },
    { word: "mögen", meaning: "to like" },
    { word: "Frage", meaning: "question" },
    { word: "gar", meaning: "at all" },
    { word: "zeigen", meaning: "to show" },
    { word: "führen", meaning: "to lead" },
    { word: "möglich", meaning: "possible" },
    { word: "sprechen", meaning: "to speak" },
    { word: "während", meaning: "during; while, whereas" },
    { word: "Haus", meaning: "house" },
    { word: "Fall", meaning: "case; fall" },
    { word: "eigen", meaning: "one's own" },
    { word: "bringen", meaning: "to bring, take" },
    { word: "Leute", meaning: "people" },
    { word: "schön", meaning: "beautiful, pleasant, good" },
    { word: "einige", meaning: "a few, some" },
    { word: "bereits", meaning: "already" },
    { word: "Arbeit", meaning: "work" },
    { word: "leben", meaning: "to live" },
    { word: "fahren", meaning: "to drive, ride, go" },
    { word: "meinen", meaning: "to think, have an opinion" },
    { word: "spät", meaning: "late" },
    { word: "etwa", meaning: "about, approximately; perhaps" },
    { word: "wer", meaning: "who, whoever" },
    { word: "Prozent", meaning: "percent" },
    { word: "fragen", meaning: "to ask" },
    { word: "gerade", meaning: "just, just now; straight" },
    { word: "wichtig", meaning: "important" },
    { word: "zwar", meaning: "admittedly, to be precise" },
    { word: "Hand", meaning: "hand" },
    { word: "wirklich", meaning: "real, actual" },
    { word: "kennen", meaning: "to know" },
    { word: "weitere", meaning: "additional" },
    { word: "genau", meaning: "exact" },
    { word: "jung", meaning: "young" },
    { word: "gelten", meaning: "to be valid" },
    { word: "Stadt", meaning: "city" },
    { word: "Herr", meaning: "gentleman, Mr." },
    { word: "Teil", meaning: "part" },
    { word: "Problem", meaning: "problem" },
    { word: "Welt", meaning: "world" },
    { word: "jedoch", meaning: "however" },
    { word: "stellen", meaning: "to place, set" },
    { word: "darauf", meaning: "on it, to it" },
    { word: "bisschen", meaning: "little bit" },
    { word: "vier", meaning: "four" },
    { word: "nie", meaning: "never" },
    { word: "spielen", meaning: "to play" },
    { word: "denen", meaning: "to/for whom/that" },
    { word: "Recht", meaning: "right, law; all right; rather" },
    { word: "arbeiten", meaning: "to work" },
    { word: "brauchen", meaning: "to need" },
    { word: "folgen", meaning: "to follow" },
    { word: "lernen", meaning: "to learn" },
    { word: "Ende", meaning: "end" },
    { word: "kurz", meaning: "short" },
    { word: "Million", meaning: "million" },
    { word: "stark", meaning: "strong" },
    { word: "Schule", meaning: "school" },
    { word: "Woche", meaning: "week" },
    { word: "bestehen", meaning: "to exist, insist, pass (an exam)" },
    { word: "richtig", meaning: "right, correct" },
    { word: "dich", meaning: "you" },
    { word: "dafür", meaning: "for it" },
    { word: "sowie", meaning: "as well as" },
    { word: "oft", meaning: "often" },
    { word: "Vater", meaning: "father" },
    { word: "Seite", meaning: "side, page" },
    { word: "verschieden", meaning: "different" },
    { word: "halt", meaning: "just, simply" },
    { word: "Leben", meaning: "life" },
    { word: "allerdings", meaning: "though, indeed, certainly" },
    { word: "verstehen", meaning: "to understand" },
    { word: "fast", meaning: "almost" },
    { word: "wohl", meaning: "well, probably" },
    { word: "dein", meaning: "your" },
    { word: "bestimmt", meaning: "special, certain" },
    { word: "Mutter", meaning: "mother" },
    { word: "setzen", meaning: "to set, place, put" },
    { word: "überhaupt", meaning: "at all, generally" },
    { word: "Grund", meaning: "reason, basis" },
    { word: "besser", meaning: "better" },
    { word: "dir", meaning: "to/for you" },
    { word: "schnell", meaning: "fast" },
    { word: "bekommen", meaning: "to get, receive" },
    { word: "gern(e)", meaning: "gladly" },
    { word: "Auge", meaning: "eye" },
    { word: "sicher", meaning: "safe, secure, certain" },
    { word: "davon", meaning: "from it, about it, thereof" },
    { word: "beginnen", meaning: "to begin" },
    { word: "erzählen", meaning: "to narrate, tell" },
    { word: "versuchen", meaning: "to try, attempt" },
    { word: "besonders", meaning: "especially" },
    { word: "Wort", meaning: "word" },
    { word: "neben", meaning: "beside, next to" },
    { word: "schreiben", meaning: "to write" },
    { word: "warum", meaning: "why" },
    { word: "nächst-", meaning: "next" },
    { word: "laufen", meaning: "to run" },
    { word: "Geld", meaning: "money" },
    { word: "erklären", meaning: "to explain" },
    { word: "Sache", meaning: "thing" },
    { word: "Art", meaning: "kind, type" },
    { word: "politisch", meaning: "political" },
    { word: "entsprechen", meaning: "to correspond to" },
    { word: "klar", meaning: "clear" },
    { word: "schwer", meaning: "difficult, heavy" },
    { word: "Bereich", meaning: "area, region" },
    { word: "allein(e)", meaning: "alone" },
    { word: "kaum", meaning: "hardly" },
    { word: "Weg", meaning: "way" },
    { word: "sitzen", meaning: "to sit" },
    { word: "Stunde", meaning: "hour" },
    { word: "einzeln", meaning: "individual" },
    { word: "deshalb", meaning: "for that reason" },
    { word: "deren", meaning: "whose" },
    { word: "ziehen", meaning: "to pull, move" },
    { word: "na", meaning: "well" },
    { word: "beziehungsweise", meaning: "and/or" },
    { word: "sogar", meaning: "even, in fact" },
    { word: "Name", meaning: "name" },
    { word: "damals", meaning: "back then" },
    { word: "fünf", meaning: "five" },
    { word: "Geschichte", meaning: "history, story" },
    { word: "wegen", meaning: "because of" },
    { word: "Gesellschaft", meaning: "society, company" },
    { word: "scheinen", meaning: "to shine, seem, appear" },
    { word: "darüber", meaning: "above it, about it" },
    { word: "fallen", meaning: "to fall" },
    { word: "Kopf", meaning: "head" },
    { word: "gehören", meaning: "to belong to" },
    { word: "entstehen", meaning: "to originate" },
    { word: "bekannt", meaning: "well-known" },
    { word: "erhalten", meaning: "to receive" },
    { word: "Paar", meaning: "pair, couple" },
    { word: "leicht", meaning: "light, easy" },
    { word: "Möglichkeit", meaning: "possibility" },
    { word: "treffen", meaning: "to meet" },
    { word: "hinter", meaning: "behind" },
    { word: "sonst", meaning: "otherwise" },
    { word: "daran", meaning: "on it" },
    { word: "Unternehmen", meaning: "enterprise, company" },
    { word: "weiter", meaning: "further" },
    { word: "suchen", meaning: "to search, look for" },
    { word: "Bild", meaning: "picture" },
    { word: "Buch", meaning: "book" },
    { word: "legen", meaning: "to put, lay" },
    { word: "Wasser", meaning: "water" },
    { word: "Stelle", meaning: "place" },
    { word: "vor•stellen", meaning: "to introduce, imagine" },
    { word: "Form", meaning: "form, shape" },
    { word: "handeln", meaning: "to deal, trade" },
    { word: "Mark", meaning: "mark (former unit of German currency)" },
    { word: "Entwicklung", meaning: "development" },
    { word: "Monat", meaning: "month" },
    { word: "erreichen", meaning: "to reach, achieve" },
    { word: "anders", meaning: "different(ly)" },
    { word: "schließlich", meaning: "in the end, finally" },
    { word: "tragen", meaning: "to carry, wear" },
    { word: "eher", meaning: "earlier, more likely, rather" },
    { word: "Familie", meaning: "family" },
    { word: "Morgen", meaning: "morning; tomorrow" },
    { word: "je", meaning: "ever, each" },
    { word: "Abend", meaning: "evening" },
    { word: "zehn", meaning: "ten" },
    { word: "darin", meaning: "in it, inside" },
    { word: "rund", meaning: "round; approximately" },
    { word: "Aufgabe", meaning: "assignment, task, job" },
    { word: "frei", meaning: "free" },
    { word: "Universität", meaning: "university" },
    { word: "schaffen", meaning: "to manage; to create" },
    { word: "Sinn", meaning: "sense, meaning" },
    { word: "früh", meaning: "early" },
    { word: "lesen", meaning: "to read" },
    { word: "Staat", meaning: "state" },
    { word: "Ziel", meaning: "goal, destination" },
    { word: "gegenüber", meaning: "opposite" },
    { word: "Freund", meaning: "friend" },
    { word: "Thema", meaning: "theme, topic, subject" },
    { word: "unterschiedlich", meaning: "different" },
    { word: "daher", meaning: "from there, therefore" },
    { word: "Person", meaning: "person" },
    { word: "schlecht", meaning: "bad" },
    { word: "Euro", meaning: "euro (unit of currency of the EU)" },
    { word: "obwohl", meaning: "although" },
    { word: "Nacht", meaning: "night" },
    { word: "verlieren", meaning: "to lose" },
    { word: "Ding", meaning: "thing" },
    { word: "deutlich", meaning: "clear" },
    { word: "allgemein", meaning: "general" },
    { word: "Raum", meaning: "room, space" },
    { word: "Blick", meaning: "look, view, glance" },
    { word: "einzig", meaning: "only, single" },
    { word: "dar•stellen", meaning: "to depict, portray" },
    { word: "Platz", meaning: "place, room, square" },
    { word: "Zahl", meaning: "number" },
    { word: "gemeinsam", meaning: "common, mutual" },
    { word: "nah", meaning: "near, close" },
    { word: "System", meaning: "system" },
    { word: "Uhr", meaning: "clock" },
    { word: "dessen", meaning: "whose" },
    { word: "Eltern", meaning: "parents" },
    { word: "erkennen", meaning: "to recognize" },
    { word: "entwickeln", meaning: "to develop" },
    { word: "früher", meaning: "earlier, in former times" },
    { word: "Straße", meaning: "street" },
    { word: "reden", meaning: "to talk" },
    { word: "voll", meaning: "full" },
    { word: "aus•sehen", meaning: "to appear, look" },
    { word: "erscheinen", meaning: "to appear" },
    { word: "mehrere", meaning: "several" },
    { word: "Minute", meaning: "minute" },
    { word: "zunächst", meaning: "first, at first, for now" },
    { word: "Gruppe", meaning: "group" },
    { word: "Wert", meaning: "value; worth" },
    { word: "Gesicht", meaning: "face" },
    { word: "irgendwie", meaning: "somehow" },
    { word: "Sprache", meaning: "language" },
    { word: "bilden", meaning: "to form, educate" },
    { word: "dadurch", meaning: "through it, as a result" },
    { word: "direkt", meaning: "direct, straight" },
    { word: "international", meaning: "international" },
    { word: "sozial", meaning: "social" },
    { word: "an•fangen", meaning: "to begin" },
    { word: "best-", meaning: "best" },
    { word: "bisher", meaning: "until now" },
    { word: "erwarten", meaning: "to expect" },
    { word: "Anfang", meaning: "beginning" },
    { word: "nämlich", meaning: "namely" },
    { word: "jen-", meaning: "that, those" },
    { word: "wohnen", meaning: "to live" },
    { word: "rot", meaning: "red" },
    { word: "offen", meaning: "open" },
    { word: "Ort", meaning: "place, town, location" },
    { word: "naja", meaning: "well ..." },
    { word: "Moment", meaning: "moment" },
    { word: "betreffen", meaning: "to affect, concern" },
    { word: "meist-", meaning: "most" },
    { word: "warten", meaning: "to wait" },
    { word: "Folge", meaning: "result, consequence, series" },
    { word: "ab", meaning: "from" },
    { word: "besonder-", meaning: "special" },
    { word: "gewiss", meaning: "certain" },
    { word: "Interesse", meaning: "interest" },
    { word: "manchmal", meaning: "sometimes" },
    { word: "Milliarde", meaning: "billion" },
    { word: "Rolle", meaning: "role" },
    { word: "jemand", meaning: "someone" },
    { word: "vergehen", meaning: "to elapse; to decay" },
    { word: "öffentlich", meaning: "public" },
    { word: "Tür", meaning: "door" },
    { word: "Schüler", meaning: "pupil, student (primary and secondary level)" },
    { word: "Bedeutung", meaning: "meaning" },
    { word: "Text", meaning: "text" },
    { word: "ach", meaning: "oh" },
    { word: "Ergebnis", meaning: "result" },
    { word: "helfen", meaning: "to help" },
    { word: "Krieg", meaning: "war" },
    { word: "sechs", meaning: "six" },
    { word: "niemand", meaning: "nobody" },
    { word: "gewinnen", meaning: "to win" },
    { word: "halb", meaning: "half" },
    { word: "schließen", meaning: "to close" },
    { word: "Weise", meaning: "way, manner" },
    { word: "Regierung", meaning: "government" },
    { word: "wahrscheinlich", meaning: "probable; probably" },
    { word: "europäisch", meaning: "European" },
    { word: "Stück", meaning: "piece" },
    { word: "Wohnung", meaning: "apartment" },
    { word: "fühlen", meaning: "to feel" },
    { word: "Gespräch", meaning: "conversation" },
    { word: "bieten", meaning: "to offer" },
    { word: "interessieren", meaning: "to interest; to be interested" },
    { word: "wesentlich", meaning: "essential, fundamental" },
    { word: "erinnern", meaning: "to remind; to remember" },
    { word: "Meter", meaning: "meter" },
    { word: "her", meaning: "away from" },
    { word: "Punkt", meaning: "dot, point, period" },
    { word: "Situation", meaning: "situation" },
    { word: "ähnlich", meaning: "similar" },
    { word: "ergeben", meaning: "to result in, yield" },
    { word: "dagegen", meaning: "against it, on the other hand" },
    { word: "häufig", meaning: "frequent" },
    { word: "Lehrer", meaning: "teacher" },
    { word: "an•bieten", meaning: "to offer" },
    { word: "ebenso", meaning: "just as, as well" },
    { word: "studieren", meaning: "to study" },
    { word: "danach", meaning: "after it, afterwards" },
    { word: "Preis", meaning: "price, prize" },
    { word: "Abbildung", meaning: "illustration" },
    { word: "Begriff", meaning: "concept, idea, term" },
    { word: "Funktion", meaning: "function" },
    { word: "verbinden", meaning: "to connect, link" },
    { word: "ziemlich", meaning: "quite, fairly" },
    { word: "an•sehen", meaning: "to look at, watch" },
    { word: "Boden", meaning: "ground, floor, bottom" },
    { word: "fehlen", meaning: "to lack, to be missing, be absent" },
    { word: "Jahrhundert", meaning: "century" },
    { word: "Sohn", meaning: "son" },
    { word: "Werk", meaning: "work; factory" },
    { word: "bedeuten", meaning: "to mean" },
    { word: "schwarz", meaning: "black" },
    { word: "vergleichen", meaning: "to compare" },
    { word: "außerdem", meaning: "besides, in addition" },
    { word: "inzwischen", meaning: "in the meantime" },
    { word: "sofort", meaning: "immediately" },
    { word: "steigen", meaning: "to climb, increase" },
    { word: "Stimme", meaning: "voice" },
    { word: "acht", meaning: "eight" },
    { word: "plötzlich", meaning: "suddenly" },
    { word: "Rahmen", meaning: "frame, framework" },
    { word: "Richtung", meaning: "direction" },
    { word: "völlig", meaning: "complete" },
    { word: "nutzen", meaning: "to use" },
    { word: "Programm", meaning: "program, schedule" },
    { word: "Angst", meaning: "fear, anxiety" },
    { word: "gering", meaning: "low, small" },
    { word: "Information", meaning: "information" },
    { word: "Kunst", meaning: "art" },
    { word: "Musik", meaning: "music" },
    { word: "schauen", meaning: "to look" },
    { word: "schwierig", meaning: "difficult" },
    { word: "Politik", meaning: "politics" },
    { word: "verlassen", meaning: "to leave" },
    { word: "manch-", meaning: "some, many a" },
    { word: "bald", meaning: "soon" },
    { word: "ein•setzen", meaning: "to put in, insert" },
    { word: "Beruf", meaning: "occupation, job, profession" },
    { word: "praktisch", meaning: "practical" },
    { word: "ändern", meaning: "to change" },
    { word: "genug", meaning: "enough" },
    { word: "persönlich", meaning: "personal(ly)" },
    { word: "wachsen", meaning: "to grow" },
    { word: "aus•gehen", meaning: "to go out; assume" },
    { word: "Regel", meaning: "rule" },
    { word: "Schritt", meaning: "step" },
    { word: "-jährig", meaning: "-year-old" },
    { word: "Absatz", meaning: "sales; paragraph; heel" },
    { word: "geschehen", meaning: "to happen, occur" },
    { word: "Gott", meaning: "god; God" },
    { word: "Auto", meaning: "car" },
    { word: "beschreiben", meaning: "to describe" },
    { word: "Beziehung", meaning: "relation, relationship" },
    { word: "Erfahrung", meaning: "experience" },
    { word: "Tisch", meaning: "table" },
    { word: "an•nehmen", meaning: "to accept, assume" },
    { word: "endlich", meaning: "finally, at last" },
    { word: "kriegen", meaning: "to get, receive" },
    { word: "Zukunft", meaning: "future" },
    { word: "planen", meaning: "to plan" },
    { word: "Spiel", meaning: "game" }
  ];