export const examples = [
    "Im Deutschunterricht lernen wir 'der / die / das'.",
    "Ich mag Äpfel und Bananen.",
    "Ich versuche, freundlich zu sein.",
    "Ich bin in der Schule.",
    "Ich sehe ein Haus.",
    "Ich gehe zu meiner Freundin.",
    "Ich habe ein Buch.",
    "Ich spiele im Park.",
    "Ich werde groß.",
    "Sie ist meine Freundin.",
    "Ich komme von der Schule.",
    "Ich bin nicht müde.",
    "Ich gehe mit meinem Hund spazieren.",
    "Es ist kalt.",
    "Er freut sich über das Geschenk.",
    "Ich mag auch Kuchen.",
    "Das Buch liegt auf dem Tisch.",
    "Das Geschenk ist für dich.",
    "Ich denke an dich.",
    "Er spielt Fußball.",
    "Das ist so einfach.",
    "Ich weiß, dass es regnet.",
    "Kinder können spielen.",
    "Dies ist mein Auto.",
    "Er ist größer als ich.",
    "Das ist ihr Hund.",
    "Ja, ich komme.",
    "Wie geht es dir?",
    "Ich bin bei meiner Freundin.",
    "Möchtest du Tee oder Kaffee?",
    "Wir gehen spazieren.",
    "Ich mag Pizza, aber ich esse auch Salat.",
    "Ich spiele und dann lerne ich.",
    "Man sollte freundlich sein.",
    "Da ist ein schöner Park.",
    "Das ist sein Ball.",
    "Ich habe noch Hunger.",
    "Ich gehe nach Hause.",
    "Was machst du?",
    "Also, ich gehe jetzt.",
    "Ich komme aus Deutschland.",
    "All meine Freunde sind hier.",
    "Wenn es regnet, bleibe ich zu Hause.",
    "Ich habe nur einen Hund.",
    "Wir müssen lernen.",
    "Ich sage hallo.",
    "Wir treffen uns um acht Uhr.",
    "Wir sprechen über das Wetter.",
    "Ich mache meine Hausaufgaben.",
    "Ich habe kein Geld.",
    "Das Jahr beginnt im Januar.",
    "Du bist nett.",
    "Das ist mein Auto.",
    "Ich habe schon gegessen.",
    "Ich warte vor dem Haus.",
    "Das Licht scheint durch das Fenster.",
    "Ich gebe dir ein Buch.",
    "Ich möchte mehr Wasser.",
    "Ich sehe einen anderen Hund.",
    "Ich habe viel zu lernen.",
    "Ich komme aus Berlin.",
    "Ich lerne jetzt Deutsch.",
    "Du sollst deine Hausaufgaben machen.",
    "Gib mir das Buch.",
    "Ich will ein Eis.",
    "Ich bin ganz glücklich.",
    "Er sieht mich.",
    "Ich trinke immer Wasser.",
    "Ich gehe zur Schule.",
    "Das ist sehr gut.",
    "Ich bin hier.",
    "Ich wollte gehen, doch blieb ich.",
    "Ich warte bis zehn Uhr.",
    "Der Hund ist groß.",
    "Ich sehe dich wieder.",
    "Ich habe es einmal gemacht.",
    "Ich habe zwei Katzen.",
    "Das Essen ist gut.",
    "Ich will es wissen.",
    "Ich habe ein neues Buch.",
    "Ich sehe den Vogel.",
    "Lass uns gehen.",
    "Er ruft uns an.",
    "Ich lerne, weil ich Deutsch mag.",
    "Das Buch liegt unter dem Tisch.",
    "Ich esse, denn ich habe Hunger.",
    "Ich stehe am Fenster.",
    "Jeder Mensch ist wichtig.",
    "Das ist ein gutes Beispiel.",
    "Die Zeit ist kostbar.",
    "Ich lese das erste Buch.",
    "Ich gebe ihm das Spielzeug.",
    "Ich sehe ihn im Park.",
    "Wo ist das Haus?",
    "Der Weg ist lang.",
    "Eigentlich bin ich müde.",
    "Ich übe, damit ich besser Deutsch spreche.",
    "Ich mache es selbst.",
    "Das ist unser Haus.",
    "Die Vögel fliegen oben.",
    "Ich habe drei Äpfel.",
    "Ich habe wenig Zeit.",
    "Die Frau ist nett.",
    "Der Mensch ist freundlich.",
    "Ich lerne Deutsch.",
    "Das Kind spielt im Garten.",
    "Ich esse etwas Brot.",
    "Der Tag ist schön.",
    "Nun beginnt die Stunde.",
    "Ich kann den Schlüssel finden.",
    "Ich sehe nichts.",
    "Ich bleibe zu Hause.",
    "Ich trinke keinen Kaffee, sondern Tee.",
    "Das Haus ist klein.",
    "Der Park liegt zwischen den Häusern.",
    "Mein Großvater ist alt.",
    "Ich bin gegen Krieg.",
    "Die Katze liegt im Korb.",
    "Ich gehe ohne Jacke.",
    "Nein, danke.",
    "Heute ist ein schöner Tag.",
    "Das Dorf ist weit weg.",
    "Ich heiße Anna.",
    "Ich denke an dich.",
    "Ich bin eben angekommen.",
    "Ich komme erst später.",
    "Natürlich komme ich.",
    "Ich weiß nicht, ob es regnet.",
    "Der Turm ist hoch.",
    "Beide Hunde spielen.",
    "Der Mann liest die Zeitung.",
    "Das Essen ist einfach.",
    "Vielleicht gehe ich spazieren.",
    "Dort ist mein Freund.",
    "Ich bin dabei.",
    "Ich habe es einmal gesehen.",
    "Ich gebe ihnen das Buch.",
    "Welches Buch liest du?",
    "Ich nehme einen Apfel.",
    "Was tust du?",
    "Ich lerne Deutsch seit einem Jahr.",
    "Ich darf spielen.",
    "Ich glaube an Wunder.",
    "Er hält die Tasse.",
    "Ich nenne meinen Hund Max.",
    "Deutschland ist ein Land.",
    "Das war mein letztes Buch.",
    "Ich komme gleich.",
    "Solch ein Problem habe ich nicht.",
    "Ich esse Brot und dazu trinke ich Milch.",
    "Ich mag Schokolade.",
    "Ich habe eine Frage.",
    "Ich kann gar nicht schwimmen.",
    "Zeig mir dein Buch.",
    "Er führt die Gruppe.",
    "Das ist möglich.",
    "Ich spreche Deutsch.",
    "Ich lerne, während ich esse.",
    "Das Haus ist groß.",
    "In diesem Fall helfen wir.",
    "Ich habe mein eigenes Buch.",
    "Bitte bring mir das Wasser.",
    "Viele Leute sind hier.",
    "Das Wetter ist schön.",
    "Einige Kinder spielen.",
    "Ich habe bereits gegessen.",
    "Die Arbeit ist schwer.",
    "Ich will glücklich leben.",
    "Ich fahre mit dem Bus.",
    "Ich meine, es ist gut.",
    "Ich komme spät.",
    "Es sind etwa zehn Personen.",
    "Wer ist das?",
    "Fünfzig Prozent sind da.",
    "Ich frage dich.",
    "Ich komme gerade.",
    "Das ist wichtig.",
    "Er ist zwar klein, aber stark.",
    "Ich hebe meine Hand.",
    "Das ist wirklich gut.",
    "Ich kenne ihn.",
    "Ich brauche weitere Hilfe.",
    "Das ist genau richtig.",
    "Das Kind ist jung.",
    "Die Regel gilt.",
    "Die Stadt ist groß.",
    "Herr Müller kommt.",
    "Ein Teil des Kuchens ist lecker.",
    "Das ist ein Problem.",
    "Die Welt ist schön.",
    "Es regnet, jedoch bin ich glücklich.",
    "Ich stelle das Glas auf den Tisch.",
    "Ich warte darauf.",
    "Ich habe ein bisschen Hunger.",
    "Ich habe vier Äpfel.",
    "Ich esse nie Fleisch.",
    "Die Kinder spielen im Garten.",
    "Ich gebe denen das Essen.",
    "Du hast Recht.",
    "Ich arbeite heute.",
    "Ich brauche Wasser.",
    "Bitte folgen Sie mir.",
    "Ich lerne Deutsch.",
    "Das Ende ist nah.",
    "Der Film ist kurz.",
    "Die Stadt hat eine Million Einwohner.",
    "Er ist stark.",
    "Die Schule beginnt um acht.",
    "Die Woche ist lang.",
    "Ich möchte die Prüfung bestehen.",
    "Das ist richtig.",
    "Ich sehe dich.",
    "Ich bin dafür.",
    "Ich mag Tee sowie Kaffee.",
    "Ich gehe oft spazieren.",
    "Mein Vater arbeitet.",
    "Die Seite ist leer.",
    "Die Farben sind verschieden.",
    "Das ist halt so.",
    "Das Leben ist schön.",
    "Ich bin allerdings müde.",
    "Ich verstehe dich.",
    "Ich bin fast fertig.",
    "Es wird wohl regnen.",
    "Ist das dein Buch?",
    "Das ist bestimmt richtig.",
    "Meine Mutter kocht.",
    "Ich setze mich.",
    "Ich mag das überhaupt nicht.",
    "Das ist mein Grund.",
    "Heute fühle ich mich besser.",
    "Ich helfe dir.",
    "Er läuft schnell.",
    "Ich bekomme ein Geschenk.",
    "Ich esse gern Pizza.",
    "Mein Auge tut weh.",
    "Ich fühle mich sicher.",
    "Ich habe nichts davon.",
    "Wir beginnen jetzt.",
    "Er erzählt eine Geschichte.",
    "Ich versuche es.",
    "Ich mag besonders Schokolade.",
    "Das Wort ist schwierig.",
    "Ich sitze neben dir.",
    "Ich schreibe einen Brief.",
    "Warum lernst du Deutsch?",
    "Nächste Woche besuche ich dich.",
    "Ich laufe im Park.",
    "Ich spare Geld.",
    "Kannst du das erklären?",
    "Das ist eine gute Sache.",
    "Welche Art Musik magst du?",
    "Das Thema ist politisch.",
    "Das Bild entspricht der Realität.",
    "Die Antwort ist klar.",
    "Die Aufgabe ist schwer.",
    "Dieser Bereich ist interessant.",
    "Ich bin allein zu Hause.",
    "Ich habe kaum Zeit.",
    "Der Weg ist kurz.",
    "Ich sitze im Park.",
    "Die Stunde ist vorbei.",
    "Jeder Schüler arbeitet einzeln.",
    "Ich lerne, deshalb bin ich hier.",
    "Die Frau, deren Auto rot ist, fährt schnell.",
    "Ich ziehe die Tür auf.",
    "Na, wie geht es dir?",
    "Ich trinke Tee beziehungsweise Kaffee.",
    "Sogar Kinder spielen hier.",
    "Mein Name ist Anna.",
    "Damals war alles anders.",
    "Ich habe fünf Äpfel.",
    "Die Geschichte ist spannend.",
    "Wegen des Regens bleibe ich drinnen.",
    "Die Gesellschaft verändert sich.",
    "Die Sonne scheint.",
    "Wir sprechen darüber.",
    "Das Blatt fällt vom Baum.",
    "Mein Kopf tut weh.",
    "Das Buch gehört mir.",
    "Ein Problem kann entstehen.",
    "Er ist in Deutschland bekannt.",
    "Ich erhalte einen Brief.",
    "Ein Paar tanzt.",
    "Das Buch ist leicht.",
    "Ich habe eine Möglichkeit.",
    "Wir treffen uns im Park.",
    "Das Auto ist hinter dem Haus.",
    "Beeil dich, sonst kommst du zu spät.",
    "Ich denke daran.",
    "Das Unternehmen wächst.",
    "Gehe weiter geradeaus.",
    "Ich suche meinen Schlüssel.",
    "Das Bild ist schön.",
    "Das Buch ist interessant.",
    "Ich lege das Buch auf den Tisch.",
    "Ich trinke Wasser.",
    "Die Stelle ist leer.",
    "Lass mich dich vorstellen.",
    "Die Form ist rund.",
    "Wir handeln im Markt.",
    "Früher zahlten wir in Mark.",
    "Die Entwicklung ist schnell.",
    "Der Monat Januar ist kalt.",
    "Ich will mein Ziel erreichen.",
    "Jeder Mensch ist anders.",
    "Schließlich ging er nach Hause.",
    "Ich trage eine Jacke.",
    "Ich komme eher am Morgen.",
    "Meine Familie ist wichtig.",
    "Morgen gehe ich spazieren.",
    "Je mehr du lernst, desto besser.",
    "Am Abend ist es ruhig.",
    "Ich habe zehn Finger.",
    "Ich glaube daran.",
    "Das Zimmer ist rund.",
    "Die Aufgabe ist einfach.",
    "Ich bin heute frei.",
    "Er studiert an der Universität.",
    "Ich schaffe meine Arbeit.",
    "Das macht Sinn.",
    "Ich stehe früh auf.",
    "Ich lese ein Buch.",
    "Der Staat ist groß.",
    "Mein Ziel ist klar.",
    "Das Haus steht gegenüber der Schule.",
    "Mein Freund hilft mir.",
    "Das Thema ist interessant.",
    "Die Meinungen sind unterschiedlich.",
    "Ich bin müde, daher gehe ich schlafen.",
    "Jede Person ist wichtig.",
    "Das Wetter ist schlecht.",
    "Das kostet zehn Euro.",
    "Ich lerne, obwohl es schwer ist.",
    "In der Nacht ist es dunkel.",
    "Ich will nicht verlieren.",
    "Das ist ein schönes Ding.",
    "Er spricht deutlich.",
    "Das ist allgemein bekannt.",
    "Der Raum ist groß.",
    "Der Blick ist schön.",
    "Sie ist meine einzige Freundin.",
    "Das Bild stellt den Fluss dar.",
    "Der Platz ist leer.",
    "Die Zahl ist wichtig.",
    "Wir arbeiten gemeinsam.",
    "Das Geschäft ist nah.",
    "Das System ist einfach.",
    "Die Uhr zeigt zehn Uhr.",
    "Der Mann, dessen Auto blau ist, lacht.",
    "Meine Eltern sind nett.",
    "Ich erkenne dich.",
    "Er will sich entwickeln.",
    "Früher war alles anders.",
    "Die Straße ist breit.",
    "Wir reden zusammen.",
    "Das Glas ist voll.",
    "Du siehst gut aus.",
    "Der Film erscheint morgen.",
    "Mehrere Kinder spielen.",
    "Ich warte eine Minute.",
    "Zunächst esse ich Frühstück.",
    "Die Gruppe lernt zusammen.",
    "Der Wert ist hoch.",
    "Ihr Gesicht ist freundlich.",
    "Irgendwie ist es warm.",
    "Deutsch ist eine Sprache.",
    "Wir bilden eine Gruppe.",
    "Dadurch lerne ich viel.",
    "Ich fahre direkt nach Hause.",
    "Das Fest ist international.",
    "Er ist sehr sozial.",
    "Wir fangen jetzt an.",
    "Best- Freunde treffen sich oft.",
    "Bisher habe ich viel gelernt.",
    "Ich erwarte gute Noten.",
    "Der Anfang ist schwierig.",
    "Ich mag Obst, nämlich Äpfel.",
    "Jen- Problem kann gelöst werden.",
    "Ich wohne in Berlin.",
    "Die Blume ist rot.",
    "Das Fenster ist offen.",
    "Dieser Ort ist schön.",
    "Naja, ich weiß nicht.",
    "Einen Moment bitte.",
    "Das betrifft mich.",
    "Meist- esse ich gesund.",
    "Ich warte auf den Bus.",
    "Die Folge ist klar.",
    "Der Zug fährt ab Berlin.",
    "Besonder- Momente sind schön.",
    "Ich bin gewiss, dass es klappt.",
    "Ich habe Interesse an Musik.",
    "Manchmal lese ich ein Buch.",
    "Die Firma kostet eine Milliarde.",
    "Er spielt die Hauptrolle.",
    "Jemand ruft an.",
    "Die Zeit vergeht schnell.",
    "Die Bibliothek ist öffentlich.",
    "Die Tür ist offen.",
    "Der Schüler lernt fleißig.",
    "Die Bedeutung ist klar.",
    "Der Text ist einfach.",
    "Ach, ich habe Hunger.",
    "Das Ergebnis ist gut.",
    "Kannst du mir helfen?",
    "Der Krieg ist vorbei.",
    "Ich habe sechs Bleistifte.",
    "Niemand ist hier.",
    "Wir wollen gewinnen.",
    "Ich habe das Buch halb gelesen.",
    "Bitte schließen Sie die Tür.",
    "Das ist eine schöne Weise.",
    "Die Regierung arbeitet.",
    "Es wird wahrscheinlich regnen.",
    "Die Musik ist europäisch.",
    "Ein Stück Kuchen ist lecker.",
    "Die Wohnung ist klein.",
    "Ich fühle mich gut.",
    "Wir führen ein Gespräch.",
    "Die Firma bietet gute Arbeit.",
    "Ich interessiere mich für Musik.",
    "Das ist wesentlich wichtig.",
    "Ich erinnere mich an dich.",
    "Das Seil ist zwei Meter lang.",
    "Komm her!",
    "Setz einen Punkt am Ende.",
    "Die Situation ist schwierig.",
    "Die Häuser sind ähnlich.",
    "Die Arbeit ergibt Erfolg.",
    "Ich bin dagegen.",
    "Ich gehe häufig spazieren.",
    "Der Lehrer erklärt gut.",
    "Sie bieten Hilfe an.",
    "Ich mag Kaffee ebenso wie Tee.",
    "Ich studiere an der Uni.",
    "Ich esse, danach lerne ich.",
    "Der Preis ist hoch.",
    "Die Abbildung ist bunt.",
    "Der Begriff ist schwer.",
    "Die Uhr hat eine Funktion.",
    "Ich verbinde die Punkte.",
    "Das Wetter ist ziemlich kalt.",
    "Ich sehe den Film an.",
    "Der Boden ist sauber.",
    "Mir fehlt die Zeit.",
    "Im letzten Jahrhundert änderte sich alles.",
    "Mein Sohn spielt Fußball.",
    "Das Werk produziert Autos.",
    "Was soll das bedeuten?",
    "Die Katze ist schwarz.",
    "Ich vergleiche die Preise.",
    "Ich lerne Deutsch, außerdem mag ich Musik.",
    "Inzwischen ist es dunkel.",
    "Komm sofort her.",
    "Die Preise steigen.",
    "Ihre Stimme ist schön.",
    "Ich sehe acht Vögel.",
    "Plötzlich regnet es.",
    "Der Rahmen ist aus Holz.",
    "Gehe in Richtung Park.",
    "Ich bin völlig überrascht.",
    "Ich nutze mein Handy.",
    "Das Programm ist interessant.",
    "Ich habe Angst vor Spinnen.",
    "Das Risiko ist gering.",
    "Die Information ist wichtig.",
    "Ich mag moderne Kunst.",
    "Musik macht Spaß.",
    "Ich schaue den Film.",
    "Die Aufgabe ist schwierig.",
    "Politik ist interessant.",
    "Ich verlasse das Haus.",
    "Manch- Tag ist schön.",
    "Ich komme bald.",
    "Ich setze das Programm ein.",
    "Mein Beruf ist Lehrer.",
    "Das ist sehr praktisch.",
    "Ich möchte mein Zimmer ändern.",
    "Ich habe genug Zeit.",
    "Persönlich mag ich Pizza.",
    "Die Blumen wachsen schnell.",
    "Wir gehen heute aus.",
    "Die Regel ist einfach.",
    "Mach einen Schritt vorwärts.",
    "Er ist 20-jährig.",
    "Der Absatz ist kurz.",
    "Was ist geschehen?",
    "Gott segne uns.",
    "Das Auto ist neu.",
    "Kannst du das Bild beschreiben?",
    "Ihre Beziehung ist stark.",
    "Ich habe viel Erfahrung.",
    "Der Tisch ist rund.",
    "Ich nehme den Rat an.",
    "Endlich ist der Tag da.",
    "Ich kriege ein Geschenk.",
    "Die Zukunft ist ungewiss.",
    "Wir planen eine Reise.",
    "Das Spiel ist spannend."
  ];
  